"""Domain model for Market Intelligence features."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(slots=True, frozen=True)
class MarketIntelligenceFeatures:
    """Pre-computed statistical features derived from market intelligence.

    This object is generated by the application layer (Live Service or Backtester)
    and passed into the domain (MarketState). The domain does not perform rolling
    window calculations itself.
    """

    fng_value: float | None = None
    fng_z_score_30d: float | None = None
    fng_percentile_30d: float | None = None

    dvol_value: float | None = None
    dvol_z_score_30d: float | None = None
    dvol_percentile_30d: float | None = None

    pcr_value: float | None = None
